/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.moraesfausto.englishschool.view.swing;

import br.edu.utfpr.moraesfausto.englishschool.model.vo.Coordinator;
import br.edu.utfpr.moraesfausto.englishschool.model.vo.Level;
import br.edu.utfpr.moraesfausto.englishschool.model.vo.Person;
import br.edu.utfpr.moraesfausto.englishschool.model.vo.Student;
import br.edu.utfpr.moraesfausto.englishschool.model.vo.Teacher;
import java.awt.Dimension;

/**
 *
 * @author f4ustx
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainJPanel = new javax.swing.JPanel();
        studentButton = new javax.swing.JButton();
        teacherButton = new javax.swing.JButton();
        coordinatorButton = new javax.swing.JButton();
        coordinatorButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentButton.setText("Student");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        teacherButton.setText("Teacher");
        teacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherButtonActionPerformed(evt);
            }
        });

        coordinatorButton.setText("Coordinator");
        coordinatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordinatorButtonActionPerformed(evt);
            }
        });

        coordinatorButton1.setText("Level");
        coordinatorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordinatorButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordinatorButton1)
                    .addComponent(studentButton)
                    .addComponent(teacherButton)
                    .addComponent(coordinatorButton))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        mainJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coordinatorButton, coordinatorButton1, studentButton, teacherButton});

        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(studentButton)
                .addGap(18, 18, 18)
                .addComponent(teacherButton)
                .addGap(18, 18, 18)
                .addComponent(coordinatorButton)
                .addGap(18, 18, 18)
                .addComponent(coordinatorButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        Student student = new Student();
        SaveScreen saveScreen = new SaveScreen(student);
        this.mainJPanel.setPreferredSize(new Dimension(990, 990));
        this.mainJPanel.add(saveScreen);
        saveScreen.setVisible(true);
    }//GEN-LAST:event_studentButtonActionPerformed

    private void teacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherButtonActionPerformed
        // TODO add your handling code here:
        Teacher teacher = new Teacher();
        SaveScreen saveScreen = new SaveScreen(teacher);
        this.mainJPanel.setPreferredSize(new Dimension(990, 990));
        this.mainJPanel.add(saveScreen);
        saveScreen.setVisible(true);
    }//GEN-LAST:event_teacherButtonActionPerformed

    private void coordinatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordinatorButtonActionPerformed
        // TODO add your handling code here:
        Coordinator coordinator = new Coordinator();
        SaveScreen saveScreen = new SaveScreen(coordinator);
        this.mainJPanel.setPreferredSize(new Dimension(990, 990));
        this.mainJPanel.add(saveScreen);
        saveScreen.setVisible(true);
    }//GEN-LAST:event_coordinatorButtonActionPerformed

    private void coordinatorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordinatorButton1ActionPerformed
        // TODO add your handling code here:
        Level level = new Level();
        SaveScreen saveScreen = new SaveScreen(level);
        this.mainJPanel.setPreferredSize(new Dimension(990, 990));
        this.mainJPanel.add(saveScreen);
        saveScreen.setVisible(true);
    }//GEN-LAST:event_coordinatorButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void startSaveScreen(){

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coordinatorButton;
    private javax.swing.JButton coordinatorButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton studentButton;
    private javax.swing.JButton teacherButton;
    // End of variables declaration//GEN-END:variables
}
